# -*- coding: utf-8 -*-
"""homework1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ftufVPx1YvcxRL4dZAx3imcYIzgh_bXR
"""

from re import M
n = int(input())
m = n
num2 = ""
num16 = ""
while n != 0:
  num2 = str(n % 2) + num2
  n = n // 2

while m != 0:
  a = m % 16
  if a >= 0 and a <= 9:
    output = a
  elif a == 10:
    output = 'A'
  elif a == 11:
    output = 'B'
  elif a == 12:
    output = 'C'
  elif a == 13:
    output = 'D'
  elif a == 14:
    output = 'E'
  elif a == 15:
    output = 'F'
  num16 = str(output) + num16
  m = m // 16

print("二進位", num2, "十六進位", num16)